name: rocllection
version: 1.0.0+1
publish_to: none
description: Rock collection.
environment: 
  sdk: '>=2.18.2 <3.0.0'
dependencies: 
  badges: ^2.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_native_splash: ^2.2.14
  flutter_secure_storage: ^5.1.2
  fluttertoast: ^8.1.1
  go_router: ^5.1.7
  provider: ^6.0.4
  flutter: 
    sdk: flutter
  shared_preferences: ^2.0.15
  firebase_core: ^2.3.0
dev_dependencies: 
  flutter_lints: ^2.0.0
  pubspec_dependency_sorter: 0.0.2
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
